### ISSUE TITLE
Need to change googletest tag from master to main

### ISSUE THREAD

**Issue by kongty** [rdaly525/coreir#1024]
According to `googletest` repo, tag has changed from `master` to `main`.
https://github.com/google/googletest/issues/3663

Can you change cmake configuration?
`tests/gtest/CMakeLists.txt.in`

`aha-flow` cannot build docker image.

**Comment by rdaly525** [comment]
@kongty Just fixed and merged to master

**Comment by kongty** [comment]
@rdaly525 Thanks!
