### ISSUE TITLE
[python-bindings,c-api] Update COREWireableGetModuleDef to reflect C++ API name change

### ISSUE THREAD

**Issue by leonardt** [rdaly525/coreir#135]
`COREWireableGetModuleDef` -> `COREWireableGetContainer`

**Comment by rdaly525** [comment]
@leonardt, is this still an issue?

**Comment by leonardt** [comment]
Fixed by https://github.com/rdaly525/coreir/compare/dev...patch-COREWireableGetModuleDef?expand=1
