### ISSUE TITLE
[python-bindings] Fix Readme: pytest needs to be run from base dir

### ISSUE THREAD

**Issue by aniemetz** [rdaly525/coreir#179]

**Comment by leonardt** [comment]
Thanks @aniemetz !
I plan to resolve this by reorganizing the Python bindings to live in a separate repository. That will clear up this issue as all the Python related code (source and tests) will be together (rather than having the Python tests with the c/c++ tests as it is now)

**Comment by leonardt** [comment]
#202 and https://github.com/leonardt/pycoreir
