### ISSUE TITLE
branch instancepass is segfaulting on pytest

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#188]
@leonardt , Do you mind taking a look at this after Tuesday?  These are necessary changes for the cgra 1-bit stuff.

**Comment by leonardt** [comment]
Fixed in d74f91f152fa9e0cfaf525a268539b6b8888ac6a

Was failing due to these changes:
* PE numin -> numdataports
* PE has new genarg numbitports
* reg has new genargs en, clr, rst
* Add ArgBoolGet to C/Python API
