### ISSUE TITLE
Support for ROMs

### ISSUE THREAD

**Issue by leonardt** [rdaly525/coreir#204]
Option 1: Augment the memory primitive to have a readonly genarg, which would then generate a circuit with just the read ports and take a configarg with the memory initialization values

Option 2: Define a separate primitive specifically for ROMs

Thoughts? Other possibilities?

**Comment by rdaly525** [comment]
Lets set up a meeting to talk about memories specifically. I recently made a change where I defined a non-cgra specific Linebuffer Memory. I also have one for a fifo and I have a TODO to make one for a dual ported RAM.

One annoying problem with using xilinx/other IP is that they have a crazy amount of options and it is really difficult to know how to configure them. I would err on the side of more primitives with less options for memories. But I am open to discussion.
