### ISSUE TITLE
Rename simulator binary

### ISSUE THREAD

**Issue by leonardt** [rdaly525/coreir#236]
@dillonhuff @rdaly525 Can we rename the simulator binary to something like `coreir-simulator` so we can install into the system path like the coreir binary? I don't have any strong feelings about the name, but I think something a bit more specific then `simulator` would be good to avoid any name conflicts.

Another idea could be integrate it with the existing `coreir` binary so there's one frontend for all the tools, not sure if this is possible or a good idea.

**Comment by rdaly525** [comment]
I would prefer not to have this in the same binary and to keep this as a separate utility. I do agree about changing the name and including it in coreir releases as a different binary

**Comment by rdaly525** [comment]
Closing as name has changed to coreir-simulator and coreir-interpreter
