### ISSUE TITLE
Simulator segfaulting on "configs" branch

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#240]
@dillonhuff, Can you take a look at this?

These were most of the changes I made to the API
```
s/Const(/Const::make(c,/
s/Args /Values /
s/AINT/c->Int()/
s/ABOOL/c->Bool()/
s/ASTRING/c->String()/
s/Config/Mod/
```

I also made each register initialization value to be a dynamic_bit_vector (which I typedef as BitVector)
I suspect this last one is causing the segfault? 

I also notice that when I print out the BitVector values, it seems i have garbage data.

**Comment by dillonhuff** [comment]
I will take a look.

I do not understand your description of the changes to the api, for example what does:

```cpp
s/Const(/Const::make(c,/
```

mean?

**Comment by rdaly525** [comment]
Sorry for not being clear. These were my vim search and replace commands while I was updating the repo haha

For example:

```
Context* c;
Args args({{"width",Const(16)}};
```

Would turn into:
```
Context* c;
Values args({{"width",Const::make(c,16)}};
```

**Comment by rdaly525** [comment]
Feel free to stop by my office for any questions about the changes I made.

**Comment by dillonhuff** [comment]
Yeah I will walk over there now. I just pulled the configs branch and it doesnt even build from scratch when I try it on my machine.
