### ISSUE TITLE
ERROR: NYI flatten types of generator or nodef module, for Linebuffer?

### ISSUE THREAD

**Issue by dillonhuff** [rdaly525/coreir#292]
bash-3.2$ ~/CppWorkspace/coreir/bin/coreir -p rungenerators,flattentypes -i ~/CppWorkspace/CGRAMapper/examples/conv_3_1.json -o veri_conv_3_1.json --load_libs ~/CppWorkspace/coreir/lib/libcoreir-commonlib.dylib 
In Run Generators
ERROR: NYI flatten types of generator or nodef module
{commonlib.Linebuffer}.out Is not a flattened type!
  Type is: Bit[16][1][3]

Assertion failed: (isBitOrArrOfBits(rpair.second)), function runOnInstanceGraphNode, file flattentypes.cpp, line 69.
Abort trap: 6

**Comment by rdaly525** [comment]
@dillonhuff Can you confirm that this is fixed in dev and close the issue?

**Comment by dillonhuff** [comment]
Yes, this is fixed.
