### ISSUE TITLE
Confusing error when selecting from Type*

### ISSUE THREAD

**Issue by jeffsetter** [rdaly525/coreir#305]
// The following code compiles fine:
Type* lb_output = out_type->sel(0);

// confusing error when running is:
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid

// solution: you can’t a select an int from a Type*, use a string instead
Type* lb_output = out_type->sel(“0”);

**Comment by rdaly525** [comment]
solution would be to add an enable_if to the sel function to get rid of this weirdness
