### ISSUE TITLE
Example coreir -> magma file

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#307]
Can you create an example magma file from examples/counters.json ?

Since I am not the most familiar with magma, it will be much easier for me to write a magma backend given an example of a translation.

**Comment by leonardt** [comment]
@rdaly525 https://github.com/phanrahan/mantle/blob/master/examples/coreir/counters.py produces https://github.com/phanrahan/mantle/blob/master/examples/coreir/counters.json

let me know if you have questions
