### ISSUE TITLE
Codebase cleanup

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#32]
- [x] Remove all "using namespace xxx" from any header files

- [ ] Add License file for freeBSD license

- [x] Create a generic file comment header and add to every source file.

- [ ] Audit all the decisions to use class vs struct

- [ ] Go through all 'TODO's in code and resolve or move to a github issue

- [ ] Change code to use References rather than pointers when possible

- [ ] Add const when I can to the api. 

- [ ] Add 'explicit' to all class constructors.

- [ ] Move defaults from class constructors to class data.

**Comment by THofstee** [comment]
- [ ] Remove all `using namespace xxx` from any header files
is probably more along the lines of what we want.

**Comment by rdaly525** [comment]
Some of these are fixed by #200
