### ISSUE TITLE
API Problems and Requests

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#33]
This is a general issue for discussing problems with the coreIR API

Please comment on this github issue with API problems labeled with C++, C, or Python

Does a function cause a segfault? (If so please file a separate issue)
Does a function cause coreIR to falsely error?
Does a function produce unhelpful error messages?
Is the name of the function confusing?
Is there some basic function you want and cannot do?

**Comment by THofstee** [comment]
`libs/stdlib.hpp` has `using namespace CoreIR;` as one of the lines in the file. This seems like a potentially bad idea because now any file that #includes stdlib will now also be using the CoreIR namespace.

**Comment by rdaly525** [comment]
Totally agree. This should be added to the issue #32

**Comment by THofstee** [comment]
Can confirm that passing in nullptr as the Type* to runGenerator causes a segfault.

**Comment by jeffsetter** [comment]
The formatting for 2+ dimensional arrays seems a bit cumbersome. Perhaps some syntactic sugar to make specifically arrays easier to write?

      {"out",context->Array(3, context->Array(3,
                                              context->Array(bitwidth,context->BitOut())  )) }

**Comment by rdaly525** [comment]
@jeffsetter What is a proposed syntax?

**Comment by jeffsetter** [comment]
I was thinking that C's array syntax is fairly standard, so something like
context->BitOut()[bitwidth][3][3]

I'm not sure if this would be annoying to implement, but it looks a little cleaner to me.

**Comment by rdaly525** [comment]
@jeffsetter I have thought about doing that, the problem is that Type is a pointer. And you would have to dereference it in order to use the [] operator. 

So it would have to look like:
Type* stencil = *(*(*(context->BitOut())[bitwidth])[3])[3]

Which I would argue is uglier.

I could do:
Type* stencil = context->BitOut()->Arr(bitwidth)->Arr(3)->Arr(3)
which is a bit better.

**Comment by rdaly525** [comment]
Added in #48

**Comment by THofstee** [comment]
I believe coreir.h and coreir-c.h should replace `extern COREModuleDef* COREModuleGetDefs(COREModule* m);` with `extern COREModuleDef* COREModuleGetDef(COREModule* m);`. There is no such function named `COREModuleGetDefs`.

**Comment by cdonovick** [comment]
There is currently no way to determine the bitwidth of a connection in python beyond inspecting the selectpath of both end points and searching for `'data'` or `'bit'` and making the assumption that:
`*.data.out -> *.data.in[*]` implies 16 bit connection and
`*.bit.out    -> *.bit.in[*]` implies 1 bit connection

It would be preferable if connections had their width.

**Comment by rdaly525** [comment]
@caleb, opened new issue #71

**Comment by THofstee** [comment]
C interface segfaults when calling `CORELoadModule` on `_add4Gen.json` from unit tests.
