### ISSUE TITLE
Using "coreir.wrap" on named types "coreir.clk" or "coreir.clkIn" fails

### ISSUE THREAD

**Issue by dillonhuff** [rdaly525/coreir#347]
The code:

```cpp
      def->addInstance("toClk0",
                       "coreir.wrap",
                       {{"type", Const::make(c, c->Named("coreir.clkIn"))}});

```

produces the error:

```bash
ERROR: NYI named type that is not Bit or BitIn
```

When rungenerators is run on json containing the toClk0 instance.

The same problem happens when I change to "coreir.clk" instead of "coreir.clkIn". Am I using this primitive correctly?

**Comment by rdaly525** [comment]
Just pushed a fix in dev.

You should be using "coreir.clk" for the type in both strip and wrap.

**Comment by dillonhuff** [comment]
The fix worked. I can now run the rtlil generators for the CGRA
