### ISSUE TITLE
simpleAetherling.cpp test is failing

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#382]

**Comment by rdaly525** [comment]
@David-Durst, Can you fix this?

**Comment by David-Durst** [comment]
https://github.com/rdaly525/coreir/pull/404 fixes this issue. Please don't merge until I've also addressed the issues in https://github.com/rdaly525/coreir/pull/397#issuecomment-365823031.

**Comment by David-Durst** [comment]
Nevermind, go ahead and merge https://github.com/rdaly525/coreir/pull/404. I have ttps://github.com/rdaly525/coreir/pull/405 to fix https://github.com/rdaly525/coreir/pull/397
