### ISSUE TITLE
Consolidate Formal Verif scripts into simple Python script with a requirements.txt

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#386]
@cristian-mattarei

**Comment by rdaly525** [comment]
@cristian-mattarei any update on this?

**Comment by cristian-mattarei** [comment]
I am working on a separate tool called CoreIR Symbolic Analyzer (https://github.com/cristian-mattarei/CoSA).

It is based on pySMT and PyCoreIR, and it currently supports:
- simulation
- safety verification
- equivalence checking
- deterministic check for transition systems

**Comment by rdaly525** [comment]
Great! I would love to see a demo of this

**Comment by rdaly525** [comment]
closing this as there is a separate repo.
