### ISSUE TITLE
JSON for register gives init = 0 even when the init parameter is non-zero?

### ISSUE THREAD

**Issue by dillonhuff** [rdaly525/coreir#392]
[This test case](https://github.com/dillonhuff/coreir/blob/misc_and_bitinout/tests/unit/save_register_init.cpp) saves a register with an "init" parameter equal to BitVec(32, 24).

When I save and re-load the module I find that the init value is zero. The JSON file saved on [this line](https://github.com/dillonhuff/coreir/blob/67d62462cab4da7f20634006e5c8c9be8af8a369/tests/unit/save_register_init.cpp#L41) looks like so:

```json
{"top":"global.regComb",
"namespaces":{
  "global":{
    "modules":{
      "regComb":{
        "type":["Record",{
          "clk":["Named","coreir.clkIn"],
          "in":["Array",32,"BitIn"],
          "out":["Array",32,"Bit"]
        }],
        "instances":{
          "reg0":{
            "genref":"coreir.reg",
            "genargs":{"width":["Int",32]},
            "modargs":{"init":[["BitVector",32],0]}
          }
        },
        "connections":[
          ["reg0.clk","self.clk"],
          ["reg0.in","self.in"],
          ["reg0.out","self.out"]
        ]
      }
    }
  }
}
}
```

**Comment by rdaly525** [comment]
This is due to #395 . The fix will be to serialize bitvectors as strings. This will be implemented in bsim

**Comment by rdaly525** [comment]
Closing
