### ISSUE TITLE
self.clk not being wired by wireclocks pass

### ISSUE THREAD

**Issue by David-Durst** [rdaly525/coreir#440]
Running the test at https://github.com/David-Durst/coreir/blob/aetherlingMultipleParallelism/tests/simulator/aetherlingHelpersSim.cpp#L151 produces the following line when trying to run the simulator (note: 0,1,2,3 are me printing out iterator): 

0
Select self.clk is not set in self.clk
Cannot execute because 1 input(s) are not set:
	self.clk
1
Select self.clk is not set in self.clk
Cannot execute because 1 input(s) are not set:
	self.clk
2
Select self.clk is not set in self.clk
Cannot execute because 1 input(s) are not set:
	self.clk
3
Select self.clk is not set in self.clk
Cannot execute because 1 input(s) are not set:
	self.clk
self.out_0_container_el0 cannot be found

**Comment by rdaly525** [comment]
This was determined to be not a bug.
