### ISSUE TITLE
Assertion failure in interpreter, possibly nested arrays?

### ISSUE THREAD

**Issue by leonardt** [rdaly525/coreir#471]
```
{"top":"global.Test",
"namespaces":{
  "global":{
    "modules":{
      "Test":{
        "type":["Record",[
          ["I",["Array",5,"BitIn"]],
          ["O",["Array",1,["Array",5,"Bit"]]]
        ]],
        "connections":[
          ["self.I","self.O.0"]
        ]
      }
    }
  }
}
}
```

Produces the following output when calling `state->execute();`
```
Starting topological sort
topo_order.size() = 2
numVertices(g)    = 2
Assertion failed: (bits.bitLength() == 1), function setValue, file interpret.cpp, line 1682.
```

Suspect nested arrays are the issue? @shacklettbp @dillonhuff any insight?

**Comment by rdaly525** [comment]
I suspect that this is because the interpreter requires flattened types. You have to call the "flattentypes" pass in order to use the interpreter. 

@dillonhuff, perhaps always calling "verifyflattenedtypes" pass during initialization of the interpreter would help prevent these issues.

**Comment by leonardt** [comment]
Makes sense. I can close this unless we plan to eventually support the ability to have non-flattened types? In that case, we can keep it open to track that feature.

**Comment by rdaly525** [comment]
I am going to close this and move it to a new bug.

**Comment by rdaly525** [comment]
Tracked in #476
