### ISSUE TITLE
pycoreir dies on opening symlinked files 

### ISSUE THREAD

**Issue by cdonovick** [rdaly525/coreir#52]
Trying to open a symlink results in:
```
ERROR: Cannot open file ../test.json


I AM DYING!
```

Clearly not a high priority bug

**Comment by leonardt** [comment]
Is this when using `context.load_from_file(..)`? If so, I'm guessing it's an issue in the coreir library since the bindings pass the file path as a string.

**Comment by rdaly525** [comment]
Seems to work, so not a bug.
