### ISSUE TITLE
Call to primitive regrst has not been updated in Mantle.hpp

### ISSUE THREAD

**Issue by JKHHai** [rdaly525/coreir#585]
In line 61 of Mantle.hpp: 
https://github.com/rdaly525/coreir/blob/4f85bab3aa1990f28bd188fdfa330050074c1839/src/ir/headers/mantle.hpp#L61
Mantle.reg calls coreir.regrst, not coreir.reg_arst. This results in an error when a mantle.reg is instantiated with a reset.

**Comment by rdaly525** [comment]
closed by #586
