### ISSUE TITLE
Array of Values

### ISSUE THREAD

**Issue by jeffsetter** [rdaly525/coreir#618]
Currently there is no way to pass an array of arguments. This is needed, for example, to set the values inside a rom.

Support for array of values is needed to fully implement a LUT for a camera pipeline application.

**Comment by rdaly525** [comment]
I added a Json type a while back. You should be able to use that to support whatever data structure you like including arrays.

**Comment by jeffsetter** [comment]
Oh, do you have an example of how to do that?

**Comment by rdaly525** [comment]
https://github.com/rdaly525/coreir/blob/master/tests/unit/valuetest.cpp

**Comment by jeffsetter** [comment]
Perfect that works!
