### ISSUE TITLE
Add CoreIR Pass That Counts Primtive Usage

### ISSUE THREAD

**Issue by David-Durst** [rdaly525/coreir#694]
Please add a pass that counts all the primitives that a design uses. For example, I would like to see all the 8 bit adders, 16 bit adders, n bit muxes, etc. 

Lower priority part of request: if possible, could it be possible to run this hierarchically? For example, if the design hasn't been flattened, could I get the amount of primitives each instance requires?

**Comment by rdaly525** [comment]
To reiterate what we talked about for the final format: For every level of module hierarch, for every coreir primitive, print out the number of instances of that primitive, and the total number of instances of that primitive for all the children.

**Comment by David-Durst** [comment]
Yes, thank you!

**Comment by rdaly525** [comment]
Done in #696
