### ISSUE TITLE
Ability to get type and bit width of connection

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#71]
Need to add this in C++, C, and python API

Option 1:
implement Type.getRawWidth()

Option 2:
~~Port over the isa, and cast functions,~~ and ArrayType.getLen()

**Comment by rdaly525** [comment]
I think the correct solution is to use issue #73 solution. Basically just have a function COREGetLen(COREType* arraytype)

**Comment by rdaly525** [comment]
@leonardt Can you add the Python api for Type.get_len()? You should throw an error if the type is not an array type. @cdonovick wanted this so he does not have to hardcode things.

**Comment by THofstee** [comment]
I actually hacked this in to my branch. I just did the following:

```
COREType* COREWireableGetType(COREWireable* w) {
    return rcast<COREType*>(rcast<Wireable*>(w)->getType());
}
```

**Comment by rdaly525** [comment]
Also implemented getSize on types.
