### ISSUE TITLE
Create bfloat div test

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/coreir#739]
(From Jeff)
Ran fp_pointwise on cpu
input(0,0) = 22 /pi = 7 (stored as 0x40e0)
input(1,0) = 10 /pi = 3.17188 (stored as 0x404b)
input(2,0) = 3.17188 /pi = 1.0078125 (stored as 0x3f81)
input(3,0) = 3.17187 /pi = 1 (stored as 0x3f80)
input(4,0) = 3.15625 /pi = 1
input(5,0) = 3.14063 /pi = 1
input(6,0) = 3.14062 /pi = 0.992188 (stored as 0x3f7e)
input(7,0) = 0.027451 /pi = 0.00866699 (stored as 0x3c0e)
input(8,0) = 0.0313726 /pi = 0.00994873 (stored as 0x3c23)
input(9,0) = 0.0352941 /pi = 0.0111694 (stored as 0x3c37)

**Comment by dillonhuff** [comment]
Added in PR #740

**Comment by rdaly525** [comment]
Merged into dev
