### ISSUE TITLE
inline=True: width cast + slice issue

### ISSUE THREAD

**Issue by splhack** [rdaly525/coreir#906]
With pycoreir v2.0.80, inline=True generated width cast + slice combination,
which does not look like valid SystemVerilog code. (The error message is from verilator lint)

    %Error: build/top.v:286:53: syntax error, unexpected '[', expecting ',' or '}'
      286 |     .RADDR({_$1_out[7:4],(16'(display_x + 16'h0002))[7:3]}),
          |                                                     ^

didn't figure out the minimal repro code yet.
inline=False or disabling width cast should be able to avoid this.

**Comment by leonardt** [comment]
Hmm looks like verilator doesn’t like us slicing off an inclined expression, we can blacklist expressions from being inclined into slice nodes in the backend

**Comment by leonardt** [comment]
Should be fixed by https://github.com/leonardt/verilogAST-cpp/pull/51
